// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdH7RydI0uOy9mNgx-4CydPkchNVQt_zk',
    appId: '1:279922208366:web:b8e1fe6bd2fd18d621407f',
    messagingSenderId: '279922208366',
    projectId: 'finalflutterproject-bddf0',
    authDomain: 'finalflutterproject-bddf0.firebaseapp.com',
    storageBucket: 'finalflutterproject-bddf0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMcWehthpnN4TSvbAg9SdZVM1DXlAU8Q',
    appId: '1:279922208366:android:2abeb11ce28978cc21407f',
    messagingSenderId: '279922208366',
    projectId: 'finalflutterproject-bddf0',
    storageBucket: 'finalflutterproject-bddf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUiDiyiFN1JnE4JJil2KkI6Ey42y2qj0',
    appId: '1:279922208366:ios:0b5027bf6ef64f9521407f',
    messagingSenderId: '279922208366',
    projectId: 'finalflutterproject-bddf0',
    storageBucket: 'finalflutterproject-bddf0.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectFlutter',
  );
}
